### ISSUE TITLE
"Invalid watch source" error if use vue-tweet in v-for

### ISSUE THREAD

**Issue by mahapo** [DannyFeliz/vue-tweet#3]
Using vue-tweet with v-for causing a "Invalid watch source".
<img width="760" alt="image" src="https://user-images.githubusercontent.com/28730855/171384940-c2e61480-18d9-4ada-8697-eb3417e3b5ae.png">

**Comment by DannyFeliz** [comment]
This should be fixed here https://github.com/DannyFeliz/vue-tweet/releases/tag/v2.0.2

**Comment by mahapo** [comment]
@DannyFeliz Issue still present. May changing props to ref would fix this. Like

`    watch(toRef(props), () => {
      renderTweet();
    });`

**Comment by DannyFeliz** [comment]
@mahapo I fixed in this PR https://github.com/DannyFeliz/vue-tweet/pull/28, sorry for being almost 2 years late 😅
